plugins {
    id 'groovy'
    id 'application'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = 'org.example.Main'
}

tasks.named('run') {
    standardInput = System.in
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:2.5.23'
    testImplementation 'org.spockframework:spock-core:2.4-groovy-2.5'
}

test {
    useJUnitPlatform()
}